FLIMS_LAAX_FIXTURE = {
    "resort": {
        "slug": "flims-laax",
        "name": "Flims Laax",
        "country_code": "CH",
        "bbox": {"south": 46.81, "west": 9.18, "north": 46.89, "east": 9.32},
        "center_lat": 46.835,
        "center_lng": 9.24,
    },
    "nodes": [
        {
            "node_key": "laax-base",
            "name": "Laax Base",
            "node_type": "village",
            "latitude": 46.806,
            "longitude": 9.257,
            "metadata_json": {},
        },
        {
            "node_key": "curnius",
            "name": "Curnius",
            "node_type": "lift_top",
            "latitude": 46.84,
            "longitude": 9.246,
            "metadata_json": {},
        },
        {
            "node_key": "nagens",
            "name": "Nagens",
            "node_type": "lift_top",
            "latitude": 46.869,
            "longitude": 9.234,
            "metadata_json": {},
        },
        {
            "node_key": "flims-village",
            "name": "Flims Village",
            "node_type": "village",
            "latitude": 46.834,
            "longitude": 9.281,
            "metadata_json": {},
        },
    ],
    "edges": [
        {
            "edge_key": "lift-laax-curnius",
            "from_node_key": "laax-base",
            "to_node_key": "curnius",
            "name": "Laax-Curnius Gondola",
            "edge_type": "lift",
            "lift_type": "gondola",
            "difficulty": None,
            "base_cost": 3.0,
            "vertical_drop": 0.0,
            "geometry_json": {"type": "LineString", "coordinates": [[9.257, 46.806], [9.246, 46.84]]},
            "metadata_json": {"source": "fixture"},
        },
        {
            "edge_key": "piste-curnius-nagens",
            "from_node_key": "curnius",
            "to_node_key": "nagens",
            "name": "Blue 64",
            "edge_type": "piste",
            "lift_type": None,
            "difficulty": "blue",
            "base_cost": 2.0,
            "vertical_drop": 310.0,
            "geometry_json": {"type": "LineString", "coordinates": [[9.246, 46.84], [9.234, 46.869]]},
            "metadata_json": {"source": "fixture"},
        },
        {
            "edge_key": "piste-curnius-flims",
            "from_node_key": "curnius",
            "to_node_key": "flims-village",
            "name": "Red 10",
            "edge_type": "piste",
            "lift_type": None,
            "difficulty": "red",
            "base_cost": 1.5,
            "vertical_drop": 520.0,
            "geometry_json": {"type": "LineString", "coordinates": [[9.246, 46.84], [9.281, 46.834]]},
            "metadata_json": {"source": "fixture"},
        },
        {
            "edge_key": "piste-nagens-flims",
            "from_node_key": "nagens",
            "to_node_key": "flims-village",
            "name": "Blue 20",
            "edge_type": "piste",
            "lift_type": None,
            "difficulty": "blue",
            "base_cost": 1.0,
            "vertical_drop": 410.0,
            "geometry_json": {"type": "LineString", "coordinates": [[9.234, 46.869], [9.281, 46.834]]},
            "metadata_json": {"source": "fixture"},
        },
    ],
}
